@ZapazAPI_HostAddress = https://localhost:7051

//Testing values:
@zapa_color = lightblue
@zapa_brand = Adidas
@zapa_model = Fabela
@zapa_sport = Tennis
@zapa_genre = Male
@zapa_size = 35.5
@zapa_available = false
@zapa_id = 36

//Gets all the sneakers in the database
GET {{ZapazAPI_HostAddress}}/api/Zapaz/zapas
Accept: application/json

###

//Getting a sneaker by brand
GET {{ZapazAPI_HostAddress}}/api/Zapaz/brand?brand={{zapa_brand}}
Accept: application/json

###

//Getting a sneaker by model
GET {{ZapazAPI_HostAddress}}/api/Zapaz/model?model={{zapa_model}}
Accept: application/json

###

//Getting a sneaker by sport
GET {{ZapazAPI_HostAddress}}/api/Zapaz/sport?sport={{zapa_sport}}
Accept: application/json

###

//Getting a sneaker by genre
GET {{ZapazAPI_HostAddress}}/api/Zapaz/genre?genre={{zapa_genre}}
Accept: application/json

###

//Getting a sneaker by color
GET {{ZapazAPI_HostAddress}}/api/Zapaz/color?color={{zapa_color}}
Accept: application/json

###

//Getting a sneaker by size
GET {{ZapazAPI_HostAddress}}/api/Zapaz/size?size={{zapa_size}}
Accept: application/json

###

//Getting a sneaker by availability
GET {{ZapazAPI_HostAddress}}/api/Zapaz/available?available={{zapa_available}}
Accept: application/json

###

//Adding a sneaker in the database
POST {{ZapazAPI_HostAddress}}/api/Zapaz/new-zapa
Accept: application/json
Content-Type: application/json
{
  "id": 0,
  "brand": "Nike",
  "model": "Structure 25 Premium",
  "sportType": "Running",
  "genre": "Female",
  "size": 35.5,
  "color": "pink",
  "price": 249999,
  "available": true,
  "stock": 10
}
###

//Modifying a sneaker in the database
PUT {{ZapazAPI_HostAddress}}/api/Zapaz/modify?id={{zapa_id}}
Accept: application/json
Content-Type: application/json
{
  "id": {{zapa_id}},
  "brand": "Nike",
  "model": "Structure 25 Premium",
  "sportType": "Running",
  "genre": "Female",
  "size": 35.5,
  "color": "pink",
  "price": 249999,
  "available": true,
  "stock": 9
}
###

//Delete a sneaker fromt he database
DELETE {{ZapazAPI_HostAddress}}/api/Zapaz/delete?id={{zapa_id}}
Accept: application/json

###


